<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="37e996a6-db59-4cfa-b1ca-756ae00da6e9" name="welras@CNK3T3J 2010-04-29 11:06:12" runUser="AD\welras" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2006">
  <TestRunConfiguration name="Local Test Run" id="b9a607c5-198a-483e-881f-484a0c7c0d45">
    <Description>This is a default test run configuration for a local test run.</Description>
    <Deployment userDeploymentRoot="C:\project\A_project\csharp\SampleLibApp\TestResults" useDefaultDeploymentRoot="false" runDeploymentRoot="C:\project\A_project\csharp\SampleLibApp\TestResults\welras_CNK3T3J 2010-04-29 11_06_12" />
    <TestTypeSpecific />
  </TestRunConfiguration>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <Times creation="2010-04-29T11:06:12.9200602+05:30" queuing="2010-04-29T11:06:14.6867666+05:30" start="2010-04-29T11:06:14.7397878+05:30" finish="2010-04-29T11:06:25.6051322+05:30" />
  <TestDefinitions>
    <UnitTest name="TestAddBookAsBook" storage="c:\project\a_project\csharp\samplelibapp\testservice\bin\debug\testservice.dll" id="c10f0df2-4fab-83d1-f9f8-7832b162573d">
      <Css projectStructure="" iteration="" />
      <Owners>
        <Owner name="" />
      </Owners>
      <Execution id="19ea1362-fc84-4fdb-94f5-f76cbf7eb537" />
      <TestMethod codeBase="C:\project\A_project\csharp\SampleLibApp\TestService\bin\Debug\TestService.dll" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="com.library.TestService.LibraryBookTest, TestService" name="TestAddBookAsBook" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="c10f0df2-4fab-83d1-f9f8-7832b162573d" executionId="19ea1362-fc84-4fdb-94f5-f76cbf7eb537" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="19ea1362-fc84-4fdb-94f5-f76cbf7eb537" testId="c10f0df2-4fab-83d1-f9f8-7832b162573d" testName="TestAddBookAsBook" computerName="CNK3T3J" duration="00:00:10.7941286" startTime="2010-04-29T11:06:14.7407882+05:30" endTime="2010-04-29T11:06:25.5971290+05:30" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d">
      <Output>
        <ErrorInfo>
          <Message>Test method com.library.TestService.LibraryBookTest.TestAddBookAsBook threw exception:  System.ServiceModel.CommunicationException: An error occurred while receiving the HTTP response to http://localhost:8731/Design_Time_Addresses/WCFServer/LibraryService/. This could be due to the service endpoint binding not using the HTTP protocol. This could also be due to an HTTP request context being aborted by the server (possibly due to the service shutting down). See server logs for more details. ---&gt;  System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---&gt;  System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---&gt;  System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host.</Message>
          <StackTrace>    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
 --- End of inner exception stack trace ---
    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
 --- End of inner exception stack trace ---
    at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
 --- End of inner exception stack trace ---
 
Server stack trace: 
   at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   at System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ClientReliableChannelBinder`1.RequestClientReliableChannelBinder`1.OnRequest(TRequestChannel channel, Message message, TimeSpan timeout, MaskingMode maskingMode)
   at System.ServiceModel.Channels.ClientReliableChannelBinder`1.Request(Message message, TimeSpan timeout, MaskingMode maskingMode)
   at System.ServiceModel.Channels.ClientReliableChannelBinder`1.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Security.SecuritySessionClientSettings`1.SecurityRequestSessionChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData&amp; msgData, Int32 type)
   at TestService.ServiceReference1.ILibraryService.GetBook(String isbn)
   at TestService.ServiceReference1.LibraryServiceClient.GetBook(String isbn) in C:\project\A_project\csharp\SampleLibApp\TestService\Service References\ServiceReference1\Reference.cs:line 199
   at com.library.TestService.LibraryBookTest.TestAddBookAsBook() in C:\project\A_project\csharp\SampleLibApp\TestService\LibraryBookTest.cs:line 82
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>